version: "3"
services:

  elasticsearch:
    hostname: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: elasticsearch1
    environment:
      - cluster.name=elastisearch-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  verify:
    image: zenika-resume-analysisbackend
    volumes:
        - ./docker-scripts:/docker-scripts
        - ./elasticsearch-data:/elasticsearch-data
    entrypoint: [ "/docker-scripts/initialize-elasticsearch.sh" ]
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet: