google:
  client:
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
          - email
          - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

logging:
  level:
    org.springframework.security: DEBUG
    fr.zenika: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost/resume
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
